### PR TITLE
Swedish volume measures

### PR DESCRIPTION
**Pull request by tirithen**
Adds Swedish measurements for cooking.

References:
msk, krm, tsk, kkp, glas https://sv.wikipedia.org/wiki/Kokboksm%C3%A5tt
kanna https://sv.wikipedia.org/wiki/Kanna_(m%C3%A5tt)

### CODE REVIEW

**Comment by ben-ng** [comment]
This is excellent, thank you! I'll use this when I'm making Swedish waffles this weekend.

**Comment by ben-ng** [comment]
Tests failed, through no fault of this pull request. I made some changes to the test suite so they work now. Merging in #44.

**Comment by ben-ng** [comment]
Or not, I got confused and merged something I had already merged. That's been reverted.

This pull request was _actually_ merged in 9cc484f9e884d07e88eb9f490b3e0cd01362d1d1.

**Comment by ben-ng** [comment]
Thank you! Published in 2.0.1.

**Comment by tirithen** [comment]
Thanks for merging these two requests and thanks for a nice module! :)

**Pull request closed without merging**
