### PR TITLE
Ton/Tonne Abbreviation

### PR DESCRIPTION
**Pull request by jessiesu**
Updated Ton/Tonne abbreviation to t.

### CODE REVIEW

**Comment by exarp1** [comment]
Nice work, Jessie!

**Comment by rjdestigter** [comment]
This will auto-merge https://github.com/ben-ng/convert-units/pull/69 as well

**Comment by rjdestigter** [comment]
@jessiesu The imperial `ton` should become `ton (US)`. The documentation linked to in https://github.com/ben-ng/convert-units/pull/69#issuecomment-336577950 prescribes `ton (US)` as the symbol for `ton (US) or short ton (UK/US)`

So confusing.

**Comment by jessiesu** [comment]
@rjdestigter Imperial `ton` has been updated to `ton (US)`

**Comment by jessiesu** [comment]
@rjdestigter Imperial ton has been updated to ton (US) for both abbreviation and names.

**Comment by ben-ng** [comment]
Hi folks,

I don't write javascript or do web development full-time anymore. Would any of you like to take over this project?

**Comment by jiminikiz** [comment]
Metric Tons/Tonnes (mt) and Tons/Tonnes have been added to the code base. See updated docs.

**Pull request closed without merging**
