### PR TITLE
Added metric and imperial Ton/Tonne to mass units

### PR DESCRIPTION
**Pull request by exarp1**
This is helpful for farmers to convert crop yield mass measurements.

### CODE REVIEW

**Comment by jiminikiz** [comment]
Yes! Please pull this, would love to use for current project.

**Comment by vmharrel** [comment]
@exarp1 - based on `UN/CEFACT Trade Facilitation Recommendations Recommendation N°. 20 - Codes for Units of Measure Used in International Trade`, the correct `abbreviation` for metric ton/tonne is `t`.  Your thoughts?

[Reference:](https://www.unece.org/tradewelcome/un-centre-for-trade-facilitation-and-e-business-uncefact/outputs/cefactrecommendationsrec-index/list-of-trade-facilitation-recommendations-n-16-to-20.html)

cc:  @jiminikiz

**Comment by rjdestigter** [comment]
If we're going to follow the specifications recommended by that document, `gal` should become `gal (US)`. @ben-ng What are your thoughts?

**Comment by ben-ng** [comment]
Hi folks,

I don't write javascript or do web development full-time anymore. Would any of you like to take over this project?

**Comment by jiminikiz** [comment]
@ben-ng I would gladly take this over.

**Comment by ben-ng** [comment]
@jiminikiz great! You now have access to the github project and the npm module.

**Comment by jiminikiz** [comment]
This has been added to the library.

**Pull request closed without merging**
